"""Add indexes to Apps and Titles

Revision ID: 9207770128d9
Revises: 78c33e9bffce

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '9207770128d9'
down_revision = '78c33e9bffce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index('idx_app_id_version', ['app_id', 'app_version'], unique=False)
        batch_op.create_index('idx_owned_type', ['owned', 'app_type'], unique=False)
        batch_op.create_index('idx_title_type', ['title_id', 'app_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_app_type'), ['app_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_owned'), ['owned'], unique=False)

    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_title_id'), ['title_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_title_id'))

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_owned'))
        batch_op.drop_index(batch_op.f('ix_apps_app_type'))
        batch_op.drop_index(batch_op.f('ix_apps_app_id'))
        batch_op.drop_index('idx_title_type')
        batch_op.drop_index('idx_owned_type')
        batch_op.drop_index('idx_app_id_version')

    # ### end Alembic commands ###
