"""Add additional indexes for performance optimization

Revision ID: a1b2c3d4e5f6
Revises: 9207770128d9

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9207770128d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        # Composite index for library_id + identified queries (used in stats)
        batch_op.create_index('idx_files_library_identified', ['library_id', 'identified'], unique=False)
        # Index for filepath lookups
        # Note: filepath already has unique constraint, but explicit index helps with joins
        try:
            batch_op.create_index('ix_files_filepath', ['filepath'], unique=False)
        except Exception:
            # Index may already exist, skip if so
            pass

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        # Composite index for timestamp + action_type queries
        batch_op.create_index('idx_activity_timestamp_action', ['timestamp', 'action_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_timestamp_action')

    with op.batch_alter_table('files', schema=None) as batch_op:
        try:
            batch_op.drop_index('ix_files_filepath')
        except Exception:
            # Index may not exist, skip if so
            pass
        batch_op.drop_index('idx_files_library_identified')

    # ### end Alembic commands ###
