"""Add added_at column to Titles

Revision ID: a1b2c3d4e5f7
Revises: 9207770128d9

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column, DateTime
from sqlalchemy.orm import sessionmaker

# revision identifiers, used by Alembic.
revision = "a1b2c3d4e5f7"
down_revision = "9207770128d9"
branch_labels = None
depends_on = None


def upgrade():
    # Add added_at column to titles table
    op.add_column("titles", Column("added_at", DateTime, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("titles", "added_at")

    # ### end Alembic commands ###
