"""Add additional indexes for performance optimization

Revision ID: a1b2c3d4e5f6
Revises: 9207770128d9

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9207770128d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    import sqlalchemy as sa
    inspector = sa.inspect(bind)
    
    files_indexes = [i['name'] for i in inspector.get_indexes('files')]
    activity_indexes = [i['name'] for i in inspector.get_indexes('activity_log')]

    with op.batch_alter_table('files', schema=None) as batch_op:
        # Composite index for library_id + identified queries (used in stats)
        if 'idx_files_library_identified' not in files_indexes:
            batch_op.create_index('idx_files_library_identified', ['library_id', 'identified'], unique=False)
        
        # Index for filepath lookups
        if 'ix_files_filepath' not in files_indexes:
            batch_op.create_index('ix_files_filepath', ['filepath'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        # Composite index for timestamp + action_type queries
        if 'idx_activity_timestamp_action' not in activity_indexes:
            batch_op.create_index('idx_activity_timestamp_action', ['timestamp', 'action_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_timestamp_action')

    with op.batch_alter_table('files', schema=None) as batch_op:
        try:
            batch_op.drop_index('ix_files_filepath')
        except Exception:
            # Index may not exist, skip if so
            pass
        batch_op.drop_index('idx_files_library_identified')

    # ### end Alembic commands ###
