"""Remote Reset Initial

Revision ID: a88adf95cc39
Revises: 
Create Date: 2026-02-16 14:38:49.849713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88adf95cc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('last_scan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('metadata_fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('titles_processed', sa.Integer(), nullable=True),
    sa.Column('titles_updated', sa.Integer(), nullable=True),
    sa.Column('titles_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_jobs',
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('titledb_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titledb_cache', schema=None) as batch_op:
        batch_op.create_index('idx_source', ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_titledb_cache_title_id'), ['title_id'], unique=True)

    op.create_table('titledb_dlcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_title_id', sa.String(length=16), nullable=False),
    sa.Column('dlc_app_id', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titledb_dlcs', schema=None) as batch_op:
        batch_op.create_index('idx_dlc_app', ['dlc_app_id'], unique=False)
        batch_op.create_index('idx_dlc_base', ['base_title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_titledb_dlcs_base_title_id'), ['base_title_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_titledb_dlcs_dlc_app_id'), ['dlc_app_id'], unique=False)

    op.create_table('titledb_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titledb_versions', schema=None) as batch_op:
        batch_op.create_index('idx_title_version', ['title_id', 'version'], unique=False)
        batch_op.create_index(batch_op.f('ix_titledb_versions_title_id'), ['title_id'], unique=False)

    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.String(), nullable=True),
    sa.Column('have_base', sa.Boolean(), nullable=True),
    sa.Column('up_to_date', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('nsuid', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('rawg_rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('playtime_main', sa.Integer(), nullable=True),
    sa.Column('playtime_extra', sa.Integer(), nullable=True),
    sa.Column('playtime_completionist', sa.Integer(), nullable=True),
    sa.Column('genres_json', sa.JSON(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('screenshots_json', sa.JSON(), nullable=True),
    sa.Column('redundant_updates_count', sa.Integer(), nullable=True),
    sa.Column('missing_dlcs_count', sa.Integer(), nullable=True),
    sa.Column('rawg_id', sa.Integer(), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('api_last_update', sa.DateTime(), nullable=True),
    sa.Column('api_source', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titles_missing_dlcs_count'), ['missing_dlcs_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_titles_redundant_updates_count'), ['redundant_updates_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_titles_title_id'), ['title_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('admin_access', sa.Boolean(), nullable=True),
    sa.Column('shop_access', sa.Boolean(), nullable=True),
    sa.Column('backup_access', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('title_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index('idx_activity_timestamp_action', ['timestamp', 'action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_token'), ['token'], unique=True)

    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('app_version', sa.BigInteger(), nullable=True),
    sa.Column('app_type', sa.String(), nullable=True),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_id', 'app_version', name='uq_apps_app_version')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index('idx_app_id_version', ['app_id', 'app_version'], unique=False)
        batch_op.create_index('idx_owned_type', ['owned', 'app_type'], unique=False)
        batch_op.create_index('idx_title_type', ['title_id', 'app_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_app_type'), ['app_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_owned'), ['owned'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('folder', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('compressed', sa.Boolean(), nullable=True),
    sa.Column('multicontent', sa.Boolean(), nullable=True),
    sa.Column('nb_content', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('identified', sa.Boolean(), nullable=True),
    sa.Column('identification_type', sa.String(), nullable=True),
    sa.Column('identification_error', sa.String(), nullable=True),
    sa.Column('identification_attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('titledb_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index('idx_files_library_identified', ['library_id', 'identified'], unique=False)
        batch_op.create_index('ix_files_filepath', ['filepath'], unique=False)

    op.create_table('title_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('banner_url', sa.String(length=512), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'source', name='uq_title_source')
    )
    with op.batch_alter_table('title_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_metadata_title_id'), ['title_id'], unique=False)

    op.create_table('title_tag',
    sa.Column('title_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['title_id'], ['titles.title_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('title_id', 'tag_id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.String(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('screenshots', sa.Text(), nullable=True),
    sa.Column('ignore_dlc', sa.Boolean(), nullable=True),
    sa.Column('ignore_update', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_title_id'), ['title_id'], unique=False)

    op.create_table('wishlist_ignore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title_id', sa.String(), nullable=False),
    sa.Column('ignore_dlcs', sa.Text(), nullable=True),
    sa.Column('ignore_updates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_id', name='uix_user_title_ignore')
    )
    with op.batch_alter_table('wishlist_ignore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_ignore_title_id'), ['title_id'], unique=False)

    op.create_table('app_files',
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id', 'file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_files')
    with op.batch_alter_table('wishlist_ignore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_ignore_title_id'))

    op.drop_table('wishlist_ignore')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_title_id'))

    op.drop_table('wishlist')
    op.drop_table('title_tag')
    with op.batch_alter_table('title_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_metadata_title_id'))

    op.drop_table('title_metadata')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index('ix_files_filepath')
        batch_op.drop_index('idx_files_library_identified')

    op.drop_table('files')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_owned'))
        batch_op.drop_index(batch_op.f('ix_apps_app_type'))
        batch_op.drop_index(batch_op.f('ix_apps_app_id'))
        batch_op.drop_index('idx_title_type')
        batch_op.drop_index('idx_owned_type')
        batch_op.drop_index('idx_app_id_version')

    op.drop_table('apps')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token'))

    op.drop_table('api_token')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action_type'))
        batch_op.drop_index('idx_activity_timestamp_action')

    op.drop_table('activity_log')
    op.drop_table('webhook')
    op.drop_table('user')
    with op.batch_alter_table('titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titles_title_id'))
        batch_op.drop_index(batch_op.f('ix_titles_redundant_updates_count'))
        batch_op.drop_index(batch_op.f('ix_titles_missing_dlcs_count'))

    op.drop_table('titles')
    with op.batch_alter_table('titledb_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titledb_versions_title_id'))
        batch_op.drop_index('idx_title_version')

    op.drop_table('titledb_versions')
    with op.batch_alter_table('titledb_dlcs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titledb_dlcs_dlc_app_id'))
        batch_op.drop_index(batch_op.f('ix_titledb_dlcs_base_title_id'))
        batch_op.drop_index('idx_dlc_base')
        batch_op.drop_index('idx_dlc_app')

    op.drop_table('titledb_dlcs')
    with op.batch_alter_table('titledb_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titledb_cache_title_id'))
        batch_op.drop_index('idx_source')

    op.drop_table('titledb_cache')
    op.drop_table('tag')
    op.drop_table('system_jobs')
    op.drop_table('metadata_fetch_log')
    op.drop_table('libraries')
    # ### end Alembic commands ###
